version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:240202668905:task-definition/service-td:15
        LoadBalancerInfo:
          ContainerName: 'sample-app'
          ContainerPort: 80

